translate = {
    "cane": 0, 
    "cavallo": 1, 
    "elefante": 2, 
    "farfalla": 3, 
    "gallina": 4, 
    "gatto": 5, 
    "mucca": 6, 
    "pecora": 7, 
    "scoiattolo": 8, 
    "ragno": 9, 
    "dog": 0, 
    "horse": 1, 
    "elephant": 2, 
    "butterfly": 3, 
    "chicken": 4, 
    "cat": 5, 
    "cow": 6, 
    "sheep": 7, 
    "squirrel": 8, 
    "spider": 9,
    0 : "dog",
    1 : "horse",
    2 : "elephant",
    3 : "butterfly",
    4 : "chicken",
    5 : "cat",
    6 : "cow",
    7 : "sheep",
    8 : "squirrel",
    9 : "spider"
}

