name: Trigger on Data Change

on:
  push:
    branches:
      - main
    paths:
      - 'path/to/data/**'

jobs:
  data_change_trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run your script # TODO, Replace command with command for training agent train.py
      run: |
        python scripts/process_data.py