name: Model Registry Update

on:
  push:
    paths:
      - 'model_registry/**'

jobs:
  update-registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run registry update script
      run: |
        python scripts/update_registry.py