name: Run tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.11", "3.12"]
        torch-version: ["2.5.1", "2.4.1", "2.3.1"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==${{ matrix.torch-version }}
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
        pip install -e .

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Authenticate with GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_KEY }}
      run: |
        echo "Authenticating with inline credentials..."
        echo "${{ secrets.GCP_KEY }}" | jq '.' > gcp-key.json
        gcloud auth activate-service-account --key-file=gcp-key.json
        gcloud config set project endless-galaxy-447815-e4

    - name: Test with pytest
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
      run: pytest tests/